### ISSUE TITLE
Profile edit deletes OTP secret and writes LDAP(?) password to DB

### ISSUE THREAD

**Issue by xTrekStorex** [ngoduykhanh/PowerDNS-Admin#237] opened 2018-04-09 07:40 UTC
When I edit my profile (on any user) it overwrites the OTP secret in the DB with an empty string.
This causes two-factor to consider any input valid, even no input at all.

![image](https://user-images.githubusercontent.com/3179810/38485149-1f05bfc2-3bd9-11e8-9fb1-ae77d9e61528.png)

So e.g. changing my name or email clears my two-factor setup. 
Also since in the DB it's changed to an empty string instead of NULL the "Enable two-factor" checkbox is unresponsive until I logout and log back in again. Then I can generate a new OTP QR code and scan it in FreeOTP. After that two-factor works again as expected. Until I change something on my profile again.

Also is it intended that passwords of LDAP users are written to the user table when a change like email is submitted - no input in the password tab? At least I think it's that password, could be some random hash though.
But shouldn't LDAP users be handled as external users as well, disabling the password tab like with SAML auth (94f8dd84fbab064ea8e2da87b930785951fb3662 & 05e24e5e46cf4a29d49304624aa5f6938beef6f3)?

![image](https://user-images.githubusercontent.com/3179810/38485352-b72cf98c-3bd9-11e8-8947-00f3170a19d9.png)

**Comment by ngoduykhanh** [comment] 2018-04-10 02:00
Fixed in commit 84d4bfa. Can you double check?

**Comment by xTrekStorex** [comment] 2018-04-10 07:39
Now I can't change anything on LDAP users (including avatar) and can't setup or disable two-factor.
Read-only name and email are fine, but shouldn't 2FA still be available through PDNSAdmin even for external auth? I hadn't looked at the OTP code section in the aforementioned commits so I didn't expect that. 

![image](https://user-images.githubusercontent.com/3179810/38540214-7790d0e2-3c9b-11e8-96fe-815d75b5d400.png)

After logging in with the new code changes all OTP secrets were cleared btw
Also there are still password hashes written to the DB at login (I flushed them via SQL before). 
Or are those just salted empty strings? I'd feel a bit uncomfortable if those were actual hashed passwords pulled from LDAP

![image](https://user-images.githubusercontent.com/3179810/38542555-66bfbe52-3ca2-11e8-8673-4422275d0fe2.png)

**Comment by ngoduykhanh** [comment] 2018-04-12 04:26
Shouldn't we consider LDAP authentication as `external_account` which is disabled in profile editing? To me, OTP is only for local authentication which provided by PowerDNS-Admin itself. The 3rd party Authentication might have their own 2FA authentication solution already.

With LDAP user, we won't store any password in local DB. Should be NULL, empty or `*`.

**Comment by xTrekStorex** [comment] 2018-04-12 07:02
I agree on the disabled profile edit. However OTP should imo still be available as even if the 3rd party auth already has 2FA, OTP is not forced - it's up to the user. So this would allow to use 2FA in PowerDNS-Admin regardless of 3rd party auth already providing it or not - which is my use case with a simple OpenLDAP for centralized credentials. 
And tbh it shouldnt concern admins if their users add a 2nd 2FA on top of the 3rd party one by enabling OTP - no security impairment, just a longer login process by choice.

So I'd say 2FA via OTP should be independent of the auth method chosen

**Comment by decode13** [comment] 2018-04-25 06:33
+1.
I agree that 2FA via OTP should be allowed no matter the auth method, because there is no other technical possibility to add 2FA for PowerDNS-Admin using LDAP.

**Comment by alexwbaule** [comment] 2018-08-21 19:55
@ngoduykhanh, i think this is a regression.
If 3rd party must provide the OTP, the powerDNS-Admin must externalize this (getting from the 3rd party) to the User.
It's more easy use the OTP from poweDNS-Admin that get 3rd party OTP and forward to the user, because you dont do a 302 redirect to auth the user, it's your login page.
I Think that AD, LDAP and Local Auth can use the OTP without problems, only fix when enable and disable it, to write the correct value in the database.

**Comment by ngoduykhanh** [comment] 2018-08-22 02:45
Ok, thanks everybody for giving your opinion about this. Commit 421ea62 will allow LDAP user to use the OTP. Current, it is on another branch, will be merged after i finish all work.

**Closed** 2019-12-16 14:19 UTC
