### ISSUE TITLE
Can't change MX record

### ISSUE THREAD

**Issue by TacoScheltema** [ngoduykhanh/PowerDNS-Admin#44] opened 2016-05-21 16:38 UTC
Hi, when edit an MX record I get a popup with a dialog asking for Server Name and Priority, like you would expect. The server name that is already in the record that I'm editing isn't pre-filled in, instead the "Server Name" field says 'undefined'.
Then, when I fill in my server name and a priority of 10 it will add a record for it like so:
`@	MX	Active	3600	10 mx1.example.com`

but when I then click 'Apply Changes' I get the following message:
`{ "msg": "Record example.com/MX 10 mx1.example.com: All data was not consumed", "status": "error" }`

Not sure if this is an issue with PowerDNS or with PowerDNS-Admin.

**Comment by ngoduykhanh** [comment] 2016-05-22 02:32
@TacoScheltema 
That error message came from pdns api. May i know which version of PowerDNS are you using? I can't reproduce the issue with PowerDNS Authoritative Server 3.4.8

**Comment by TacoScheltema** [comment] 2016-05-22 10:04
I have 3.4.1-4+deb8u5 which is the latest for my distro (Debian 8.4). I've tried to enable logging of json in powerdns (experimental-logfile option) but that doesn't seem to do anything.
Adding a new MX record produces the same error.

Should I try a different apt source to get a newer version of powerdns?

**Comment by TacoScheltema** [comment] 2016-05-22 14:35
I switched to jessie-backports and upgraded to 3.4.7-1~bpo8+1, this fixed the issue for me.
perhaps worth mentioning in the installation guide?

The steps I took were as follows:

Add the following line to /etc/apt/sources.list
`deb http://ftp.de.debian.org/debian jessie-backports main`

run
`apt-get update`

run
`apt-get -t jessie-backports install pdns-server pdns-backend-mysql`

I didn't have to change anything to my pdns.conf file.

**Comment by ivanfilippov** [comment] 2016-05-26 02:36
The issue exists in 3.4.1 and not in 3.4.2 which means it's most likely the API priority change that happened between those two releases. Here is the PowerDNS commit that contains the change:
https://github.com/PowerDNS/pdns/pull/2143/files

Here is the reference to the change in the PowerDNS documentation:
https://doc.powerdns.com/md/authoritative/upgrading/

@ngoduykhanh Do you think we should update the documentation to reflect that we only support pdns >= 3.4.2? Or we could build in some version awareness by making the record apply try again if it encounters that specific error? The API doesn't seem to have a reliable way of determining version: the console reports `May 25 20:33:33 PowerDNS Authoritative Server git-auth-3.4.1` on launch but the API reports:
<pre>
[
  {
    "type": "Server",
    "id": "localhost",
    "url": "/servers/localhost",
    "daemon_type": "authoritative",
    <strong><i>"version": "git",</i></strong>
    "config_url": "/servers/localhost/config{/config_setting}",
    "zones_url": "/servers/localhost/zones{/zone}"
  }
]
</pre>

**Comment by ngoduykhanh** [comment] 2016-05-26 02:44
@ivanfilippov : Yes, I think we should update the documentation to reflect that we only support pdns >= 3.4.2. Since there will be a lot of change with pdns api in later version, let's start supporting from v3.4.2 :).

**Comment by ivanfilippov** [comment] 2016-07-01 22:12
This has been merged and fixed.

**Closed by ivanfilippov** 2016-07-01 22:12 UTC
Labels: bug
