### ISSUE TITLE
Removing a domain does not work

### ISSUE THREAD

**Issue by wagnst** [ngoduykhanh/PowerDNS-Admin#89] opened 2016-07-17 13:40 UTC
If you want to remove a domain, this does not work. There can also NO logentry be found.
Doing this with `pdnsutil remove-zone` works.

I see a HTTP request going to `http://pdns/admin/domain/test.de/delete` and referring back to the domain list, but the domain is still in there.

**Comment by ngoduykhanh** [comment] 2016-07-19 10:43
Can you provide more information about your setup? (pdns version, backend-db)

It works fine for me.
Logs from the console.
```
[INFO] Delete domain khanh.lan successfully
[INFO] 127.0.0.1 - - [19/Jul/2016 17:41:37] "GET /admin/domain/khanh.lan/delete HTTP/1.1" 302 -
```

**Comment by ngoduykhanh** [comment] 2016-07-29 02:54
Closing the ticket as cannot reproduce

**Closed by ngoduykhanh** 2016-07-29 02:54 UTC

**Comment by wagnst** [comment] 2016-08-09 23:02
Hi @ngoduykhanh,
sorry I was on business trips. 
I am using a fresh install of 4.0.1 PowerDNS and a git fetch of this master branch on most current Debian Jessie version. Backend DB is MariaDB on its most current stable version (all managed through Puppet)
