### ISSUE TITLE
404 for all font files on docker image

### ISSUE THREAD

**Issue by zarlo** [ngoduykhanh/PowerDNS-Admin#619] opened 2019-12-20 11:38 UTC
im getting 404 errors for all the fonts on the docker image
ngoduykhanh/powerdns-admin (https://hub.docker.com/layers/ngoduykhanh/powerdns-admin/latest/images/sha256-bba536e651efd85e1ebef23c84c16bce69f60b23bcc9c392973359d5e832b9b6)

**Comment by ngoduykhanh** [comment] 2019-12-20 14:04
Can you show me a screenshot of your 404 errors from the browser?

**Comment by zarlo** [comment] 2019-12-20 14:49
![image](https://user-images.githubusercontent.com/2957727/71262533-1bfe3d00-2394-11ea-8181-c8c9989944fa.png)

**Comment by ngoduykhanh** [comment] 2019-12-20 15:29
Thanks. I can see it now.

@chrisss404 you might want to see this. In the Dockerfile, the [fonts directory was created](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docker/Dockerfile#L43), but the CSS file is not updated, it still use `src:url` to the `../node_modules` directory.

**Comment by chrisss404** [comment] 2019-12-20 15:44
@ngoduykhanh I am on it.

**Comment by chrisss404** [comment] 2019-12-20 16:27
Found the cause of this issue. With [this](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/9a1b92fbc2c338d8829900845a7f44b7bef14512#diff-d8b33f677413aa3f3d6086fc12062eb4) commit a space was added between `cssmin` and `cssrewrite`, therefore the sed regex didn't match any longer.

**Comment by ngoduykhanh** [comment] 2019-12-21 01:53
@chrisss404  Nice catch! I've merged your PR. Thanks for the quick fix

**Closed** 2019-12-21 01:53 UTC
Labels: bug
