### ISSUE TITLE
Safari and PowerDNS-Admin

### ISSUE THREAD

**Issue by alythemonk** [ngoduykhanh/PowerDNS-Admin#85] opened 2016-07-11 01:56 UTC
Doesn't work super well in Safari, especially in editing the profile area. Had to use Chrome for this. Would it be possible to solve this ? Thanks.

**Comment by TacoScheltema** [comment] 2016-07-11 18:44
Hi, thank you for your report. To help out the developers a bit, would you be able to describe what is  going wrong in safari? do you see any error messages? is the layout different in safari compared to chrome? is something not functioning in safari? 
Please provide as much information as you can, for instance the steps you took to get to the problem you're describing.

Thanks.

**Comment by ivanfilippov** [comment] 2016-07-13 04:36
@alythemonk 

Looks like a recent version of Safari is not available for Windows. Can someone with a Mac confirm or provide more insight?

**Comment by ngoduykhanh** [comment] 2016-07-13 04:46
@ivanfilippov : I am using Safari Version 9.1.1 (11601.6.17) on Mac OSX Capitan 10.11.5 and I can't reproduce the issue. Let's wait for more information from @alythemonk .

**Comment by TacoScheltema** [comment] 2016-07-13 08:24
I'm using version 9.1.1 (11601.6.17) on El Capitan as well and can't reproduce the issue either. I will install Safari on Windows to see if that shows any issues.

**Comment by TacoScheltema** [comment] 2016-07-13 08:37
@alythemonk I Just checked; Apple has discontinued Safari for Windows in 2012, The last update to Safari for Windows was 5.1.7, this version is now outdated insecure, it should not be used. The issue you are experiencing is likely caused by it being out of date and probably missing support for some new CSS/Javascript features. I suggest using Firefox or Chrome instead.

@ivanfilippov , @ngoduykhanh : I think this can be closed as invalid.

**Comment by alythemonk** [comment] 2016-07-13 12:59
Gents,


I did an update and to seems to have fixed the problem ! Sorry about the false report. Thanks.


Cheers,


ASD.






[https://ci3.googleusercontent.com/proxy/yRaxhwVs0q3BQNi_a1Q1V4QtzkrbV_dNQxBRzQGfzeM-IALUZm6kHIBMOJPFcUMy1rTrCEIW-QnCeFGgcCY0Wtv5tlkRYJk9bI4RiHi7cryJFYWZS_4mrR91iL5xOe2BNuA-Pfq_P_ZhDd0Al7Mv3J3hRIgGGlFqSUxw=s0-d-e1-ft#https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/images/566758f91e829.jpeg?override=1449614636]
Aly S Dharshi           B.Sc. Computer Science, RHCE


Technology Strategist


m. 780 722 3461                 t. 780 428 5226


e. aly@dharshi.ca<mailto:aly@dharshi.ca>                w. alydharshi.com<https://esig.ly/links/170277>



[https://ci4.googleusercontent.com/proxy/bNQnZ_OAzT2pM5qYP8TRGjDT8kihT8yW500UR2FT-10FN5QFKHjUitqciNYRy-C4zF55ZN3XWaR7GnjHgvoIr7sX7HwCU3xX4sNxnME6w4Cfd5wR1bt5xM37RFl7dAdwzSQWHy8=s0-d-e1-ft#https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/566759f7239bf.png]<https://esig.ly/links/170280>              [https://ci3.googleusercontent.com/proxy/38s1JmBP0z2F4DpdEo85jKKdYRFGVDOxx9aZtOd-zLlnjYDbA-rbLMqTENRF5H7908aQxeeDydm9LGWf7Ffb5k44ArqDoE_BggvfTdL5f901XS_qgOPcnzMPArr6QefIKjv_4v4=s0-d-e1-ft#https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/566759f7439f5.png] <https://esig.ly/links/170282>             [https://ci3.googleusercontent.com/proxy/xy6cM64ACsoEy6ESDSUswSl4Lc6JXIM6cRcKo2A9S9mwfVr1P8ltNrdPR565ur-QZVaw35zBnPDoui-f1p7-qDCj92hdu15CLfAtuG78O6MDmFvl3sIyNeFMwAp6JgKZcwsM2-k=s0-d-e1-ft#https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/56679c968bad4.png] <https://esig.ly/links/170304>




If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

[https://ci3.googleusercontent.com/proxy/u2GEyjAjMD9fAwfkyZGW5MsTRszpn0m46ihgGUQeStoOAvlSHaVKNxBH7CWQ4McVKigBGCVlXd626PDEBnJGRVMmpVhEq_qnQ1QpntUV0Ot6aXrz8rji1ZLYFUqwWbA54_8yYcw=s0-d-e1-ft#https://d3pv4gq91q59qh.cloudfront.net/images/6624/30748/icons/leaf-icon-sml.gif]Think before you print.






________________________________

**Closed** 2016-07-13 13:31 UTC
Labels: bug
